### ISSUE TITLE
web interface 

### ISSUE THREAD

**Issue by sameheddine** [Juerd/ESP-WiFiSettings#17]
HI Jured,
After connecte to my router, i don't have web interface to change SSID 
it is possible to make a modification in the code?
if so how can i do it
thank you

**Comment by Juerd** [comment]
I don't understand the question.

**Comment by sameheddine** [comment]
hi jured,
i like to use your ESP-WifiSettings to my project, after my ESP connecte to router i like to add web interface to manage same other information.
can i use your code to do that ?

**Comment by Juerd** [comment]
No, the web interface is not available in STA mode because it relies on the AP mode's WPA/PSK for authentication.

**Comment by sameheddine** [comment]
Thank you for your replay
