### ISSUE TITLE
WPS

### ISSUE THREAD

**Issue by folkertvanheusden** [Juerd/ESP-WiFiSettings#19]
Hi,

Please consider including WPS support.

I googled it and it doesn't look too complicated:
[https://bbs.espressif.com/viewtopic.php?t=1096](url)

The reason I'm asking: I found that "end-users" often find it problematic to enter the password for their wifi. Like casing, O versus 0, etc. and wps takes that problem supposedly away.

**Comment by folkertvanheusden** [comment]
Oh hang on: it is apparently not very safe, this WPS system: [https://en.wikipedia.org/wiki/Wi-Fi_Protected_Setup#Vulnerabilities](url)

**Comment by Juerd** [comment]
Thanks for the suggestion. I might accept a well-written PR for this if it doesn't use too much RAM and Flash, but I won't spend time implementing it. Because of the security issues I would never use it myself.
