### ISSUE TITLE
Compile error with expansion of macro 'F'

### ISSUE THREAD

**Issue by Richhoef** [Juerd/ESP-WiFiSettings#30]
Whenever I try to compile this library, I get compile errors saying it cannot convert `const char []` to `const __FlashStringHelper*` in assignment `#define F(string_literal) (string_literal)`.

This is my Platformio.ini file:
```
[env:esp32thing]
platform = espressif32
board = esp32thing
framework = arduino
lib_deps =
    juerd/ESP-WiFiSettings@^3.8.0
```

And this is the file being compiled:
https://github.com/Juerd/ESP-WiFiSettings/blob/master/examples/Basic/Basic.ino

The errors:
![image](https://user-images.githubusercontent.com/51912545/236694706-5d2ba65e-e223-4fb7-afe9-ed7bbb35c4b3.png)

Can anyone help me?

**Comment by Juerd** [comment]
This is due to a recent breaking change in arduino-esp32.

A fix is available at https://github.com/espressif/arduino-esp32/pull/8147. You can apply that manually, wait for the next release of arduino-esp32, or downgrade arduino-esp32 to the last working version.

**Comment by Richhoef** [comment]
Ah, that explains. Thanks!

**Comment by qguv** [comment]
You can jump the queue by telling platformio to use a particular commit of the platform package, see [this commit](https://github.com/revspace/operame/commit/e550ae4a67093edc86073433a4ed7b9187bf8c4c) for an example.

**Comment by qguv** [comment]
@Richhoef: You can jump the queue by telling platformio to use a particular commit of the platform package, see [this commit](https://github.com/revspace/operame/commit/e550ae4a67093edc86073433a4ed7b9187bf8c4c) for an example.

**Comment by Richhoef** [comment]
> @Richhoef: You can jump the queue by telling platformio to use a particular commit of the platform package, see [this commit](https://github.com/qguv/operame/commit/e550ae4a67093edc86073433a4ed7b9187bf8c4c) for an example.

Thanks!

**Comment by Juerd** [comment]
Going by the last few comments, this issue seems to have been fixed in the esp32 arduino project. Thanks to the reporter for reporting the issue, and thanks to commenters for sharing updates!
