### ISSUE TITLE
Access to hostname

### ISSUE THREAD

**Issue by mitra42** [Juerd/ESP-WiFiSettings#38]
Hostname is an exposed field of WiFiSettings, but is only documented in README for setting. 

I've like to use it, and can see how, - as the client name for MQTT - but am reluctant to trigger a case of Hyrum's law in the future if this is not a documented "feature". 

I think the only change is a trivial change to the README and I'm happy to do a PR if that is useful.

**Comment by Juerd** [comment]
A doc change PR for this would be welcome!

**Comment by mitra42** [comment]
OK - PR sent

**Comment by Juerd** [comment]
Fixed by #39

**Comment by Juerd** [comment]
Thanks!
