### ISSUE TITLE
Adding more settings to the webpage

### ISSUE THREAD

**Issue by B1ackt34** [Juerd/ESP-WiFiSettings#41]
Hello, your library looks very cool and i'd like to implement it into my project.
I have a question .. is it possible to use the webpage to save more fields and retrieve them later to use them in my code?
For example DeviceAddress of temp probes, login and password for smtp server and so on?
Thank you in advance!

**Comment by gzebrick** [comment]
Sure you can take the code and mod it all you want. You can also see my 890 WiFi pad as an example. It logs into my Kenwood.The arduino programming has lots of code examples you can build on.Sent from my iPadOn Nov 13, 2024, at 12:20 PM, B1ackt34 ***@***.***> wrote:﻿
Hello, your library looks very cool and i'd like to implement it into my project.
I have a question .. is it possible to use the webpage to save more fields and retrieve them later to use them in my code?
For example DeviceAddress of temp probes, login and password for smtp server and so on?
Thank you in advance!

**Comment by B1ackt34** [comment]
Thank you for your answer. I'm looking to edit the library to add 5 more fields to store on the ESP but i dont know where to start. It could be nice if the dev adds some help about it. The library and the page looks beautiful
