### ISSUE TITLE
arduino-esp32: Local IP is 255.255.255.255 after connection succeeds

### ISSUE THREAD

**Issue by santosrafael** [Juerd/ESP-WiFiSettings#9]
Hi,

After connecting to AP, I get the message "Connecting to WiFi SSID 'acesspoint'..255.255.255.255", so something went wrong and no connections could be established.

When I commented the [line 346](https://github.com/Juerd/ESP-WiFiSettings/blob/6955be55c0e71f536d8d15445700f6b832752377/WiFiSettings.cpp#L346) in file WiFiSettings.cpp the issue was gone.

**Comment by Juerd** [comment]
Is that on an ESP32 or ESP8266? Are you using the latest version of the ESP platform for Arduino; if not, which version are you using?

**Comment by Juerd** [comment]
Sorry, I've not been able to reproduce this problem. Can you share the smallest program you can make, that still shows the problem?

**Comment by Juerd** [comment]
No reply after >½ year; closing.
